'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''
class Solution:
    # Time: O(s+t) / Space: O(1)
    def findTheDifference(self, s: str, t: str) -> str:
        if not s: return t

        result = 0
        for char in s + t:
            result ^= ord(char)
        return chr(result)
